"""fase2_ingrediente_producto_pi_updates

Revision ID: 36ab199a8258
Revises: a60e37362a68
Create Date: 2026-06-15 08:30:18.556740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ab199a8258'
down_revision: Union[str, None] = 'a60e37362a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ingrediente: stock_cantidad NN con server_default para filas existentes
    op.add_column('ingrediente', sa.Column('stock_cantidad', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('ingrediente', 'stock_cantidad', server_default=None)

    op.add_column('ingrediente', sa.Column('deleted_at', sa.DateTime(), nullable=True))

    op.add_column('producto', sa.Column('unidad_venta_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_producto_unidad_medida', 'producto', 'unidad_medida', ['unidad_venta_id'], ['id'])

    op.add_column('producto_ingrediente', sa.Column('cantidad', sa.Numeric(precision=10, scale=3), server_default='1.000', nullable=False))
    op.alter_column('producto_ingrediente', 'cantidad', server_default=None)

    # unidad_medida_id: 3 pasos para filas existentes en producto_ingrediente
    op.add_column('producto_ingrediente', sa.Column('unidad_medida_id', sa.Integer(), nullable=True))
    op.execute("UPDATE producto_ingrediente SET unidad_medida_id = (SELECT id FROM unidad_medida WHERE simbolo = 'ud') WHERE unidad_medida_id IS NULL")
    op.alter_column('producto_ingrediente', 'unidad_medida_id', nullable=False)
    op.create_foreign_key('fk_producto_ingrediente_unidad_medida', 'producto_ingrediente', 'unidad_medida', ['unidad_medida_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'producto_ingrediente', type_='foreignkey')
    op.drop_column('producto_ingrediente', 'unidad_medida_id')
    op.drop_column('producto_ingrediente', 'cantidad')
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.drop_column('producto', 'unidad_venta_id')
    op.drop_column('ingrediente', 'deleted_at')
    op.drop_column('ingrediente', 'stock_cantidad')
    # ### end Alembic commands ###
