"""fase6_create_refresh_tokens

Revision ID: 3756d22f60f6
Revises: b8904d58f25b
Create Date: 2026-06-15 17:34:12.396261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3756d22f60f6'
down_revision: Union[str, None] = 'b8904d58f25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
